---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: muffin-currency
  labels:
    app: muffin-currency
spec:
  replicas: 2
  selector:
    matchLabels:
      app: muffin-currency
  template:
    metadata:
      labels:
        app: muffin-currency
    spec:
      containers:
      - name: muffin-currency
        image: aadan1lov/muffin-currency:1.0.0
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /rate?from=PLAIN&to=CHOKOLATE
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /rate?from=PLAIN&to=CHOKOLATE
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: muffin-currency
spec:
  selector:
    app: muffin-currency
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8080
  type: ClusterIP
